package server.server.cxf.inter;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-04-07T18:39:52.827+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://inter.mcenter.sjjhpt.sinobest.cn/", name = "IJobStatusUpdate")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface IJobStatusUpdate {

    @WebResult(name = "return", targetNamespace = "http://inter.mcenter.sjjhpt.sinobest.cn/", partName = "return")
    @WebMethod
    public java.lang.String updateJobStatus(
        @WebParam(partName = "jobID", name = "jobID")
        java.lang.String jobID,
        @WebParam(partName = "jobUID", name = "jobUID")
        java.lang.String jobUID,
        @WebParam(partName = "currState", name = "currState")
        int currState,
        @WebParam(partName = "lastState", name = "lastState")
        int lastState,
        @WebParam(partName = "lastTime", name = "lastTime")
        long lastTime,
        @WebParam(partName = "nextTime", name = "nextTime")
        long nextTime
    );
}
