package server.server.cxf.inter;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-04-07T18:39:52.827+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "IJobStatusUpdateService", 
                  wsdlLocation = "http://localhost:8800/sjjh/service/updateJobStatus?wsdl",
                  targetNamespace = "http://inter.mcenter.sjjhpt.sinobest.cn/") 
public class IJobStatusUpdateService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://inter.mcenter.sjjhpt.sinobest.cn/", "IJobStatusUpdateService");
    public final static QName IJobStatusUpdatePort = new QName("http://inter.mcenter.sjjhpt.sinobest.cn/", "IJobStatusUpdatePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8800/sjjh/service/updateJobStatus?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IJobStatusUpdateService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8800/sjjh/service/updateJobStatus?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IJobStatusUpdateService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IJobStatusUpdateService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IJobStatusUpdateService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public IJobStatusUpdateService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public IJobStatusUpdateService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public IJobStatusUpdateService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IJobStatusUpdate
     */
    @WebEndpoint(name = "IJobStatusUpdatePort")
    public IJobStatusUpdate getIJobStatusUpdatePort() {
        return super.getPort(IJobStatusUpdatePort, IJobStatusUpdate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IJobStatusUpdate
     */
    @WebEndpoint(name = "IJobStatusUpdatePort")
    public IJobStatusUpdate getIJobStatusUpdatePort(WebServiceFeature... features) {
        return super.getPort(IJobStatusUpdatePort, IJobStatusUpdate.class, features);
    }

}
